codecov:
  require_ci_to_pass: yes
  token: 7e197ab1-a237-44e6-87d0-4a690b08a94b

coverage:
  precision: 2
  round: down
  range: "70...100"

ignore:
  - "*/tests/**/*"
  - "contracts/test/*"
  - "**/*.py"       
